### ISSUE TITLE
updateApplicationUris mangles hostname if the end of a hostname matches subdomain

### ISSUE THREAD

**Issue by willtf** [cloudfoundry/cf-java-client#334] opened 2015-12-11 03:29 UTC
Scenario: your CF deployment contains the domains test.example.com, and example.com. You want to apply the the URI app-test.example.com to an application.

The function extractUriInfo will set the URI to app.test.example.com (mangling the hostname and placing it in the wrong domain) since it only matches the end of the authority string using authority.endsWith(domain) and prefers the longest domain, which it thinks is test.example.com. The host is mangled because it is set using authority.substring(0, authority.indexOf(domain) - 1) which strips the -test part of the hostname. 

extractUriInfo: https://github.com/cloudfoundry/cf-java-client/blob/v1.1.3/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClientImpl.java#L1258

**Comment by cgfrost** [comment] 2015-12-17 16:32
Duplicate of https://github.com/cloudfoundry/cf-java-client/issues/333

This has bee fixed but not released yet, we are closing in on a V1 maintenance release. I think it'll be before the new year, but make no promises.

**Closed by cgfrost** 2015-12-17 16:32 UTC
