### ISSUE TITLE
Memory leak when requesting new token

### ISSUE THREAD

**Issue by checketts** [cloudfoundry/cf-java-client#1032] opened 2020-02-04 14:29 UTC
I'm seeing memory leaks (heap growing until application crashes). The timing aligns with when my token refreshes are happening. And when doing a heap dump, it seems to be pointing to `AbstractUaaTokenProvider:requestToken`.  

Here is the heap info: 
![image](https://user-images.githubusercontent.com/416063/73753502-0ebcc800-4720-11ea-883e-f6d55cd3ae16.png)

Is clean up or a timeout required for the request?

**Comment by checketts** [comment] 2020-02-04 19:28
My current theory is that the unlimited retries here: https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/util/Operator.java#L209 might be related. I've adding some debugging and limiting it to 100 retries to see if I can get more insight into the behavior

**Comment by valentinEmpy** [comment] 2020-02-04 22:51
Just as a note, the infinite retries have been a target of the following PR:
https://github.com/cloudfoundry/cf-java-client/pull/1029
We experienced sporadic IPBased rate limit exceeded due to it and also suspected Netty connection/thread leaks, however we have not confirmed it.

**Comment by checketts** [comment] 2020-02-04 23:22
Thanks for the pointer @valentinEmpy. I'll be able to confirm the connection/thread leaks. I hard coded in a 100 time retry just to be absurd, but not infinite in an equivalent fix.

I have 3 instances that are running my code and predictably 2 of the 3 run into this leak when the token expires (20 hours in my case). Interestingly the 2 that have trouble are calling CF APIs that are remote, while the 1 that doesn't have trouble is calling the API it is hosted in.

**Comment by checketts** [comment] 2020-02-07 15:48
Should I close this now that #1029 is merged in? Or wait for a release?

**Comment by twoseat** [comment] 2020-02-07 15:57
If you're able to use the build snapshot to satisfy yourself that this handles your scenario that would be great.

**Comment by twoseat** [comment] 2020-02-07 15:58
I just spotted that you've done that already! If you're happy you can close this.

**Closed** 2020-02-07 16:10 UTC
