### ISSUE TITLE
[Question] Switch user scope for cf-java-client

### ISSUE THREAD

**Issue by LeeU1911** [cloudfoundry/cf-java-client#681] opened 2017-02-09 03:27 UTC
Hey team,

Could you please let me know if it is feasible to build the `CloudFoundryClient` by an access token (we only see `RefreshTokenGrantTokenProvider`, `PasswordGrantTokenProvider`, `OneTimePasscodeTokenProvider`, `ClientCredentialsGrantTokenProvider`)? Should there be something like `AccessTokenGrantTokenProvider`?

Currently in our use case, users log in using OAuth2, if successful, we retrieve the access token in Spring's Security Context and put that into Authorization header of request to query data from Cloud Controller Rest endpoints manually. Do you think it's feasible to switch to use `cf-java-client` instead? If so, how?

To be honest, we really hope to be able to use the lib since current process is very tedious and error-prone as you have to communicate to rest endpoints and parse those responses manually.

Please share if you have any idea.

Thank you,
Tom

**Comment by nebhale** [comment] 2017-02-09 15:46
The `TokenProvider` interface was designed specifically and explicitly for this purpose (Spring Security was the exact use-case we were designing for). 

`TokenProvider`'s `Mono<String> getToken(ConnectionContext)` method implies that you can get a token from pretty much anywhere.  Out of the box we provide a number of implementations for negotiating a token with the UAA (the most common use-case), but by no means are these the only way to do so.  We haven't implemented the `SecurityContextHolder` strategy simply because no one has requested or contributed it directly yet, but it should be too hard to implement on your own.

Now that we have a request for it, we'll take a look at delivering it.  If you want to build one yourself, it'll probably only be 5-10 lines, and you may want to submit a PR with your implementation to get it into the mainline project more quickly.

**Comment by nebhale** [comment] 2017-02-09 21:28
I've been looking at this today, and now I'm not quite sure if this is possible.  One of the key bits of the client is that it is asynchronous and non-blocking meaning that it switches threads pretty regularly.  Since `SecurityContextHolder` is based on `ThreadLocal` objects, it's not clear that the incoming token can be accessed at all points in the request flows.  I'll keep thinking about this.

**Comment by LeeU1911** [comment] 2017-02-10 13:31
Thank you for your responses. I really appreciate it.

I think you're right about the latest point. As I'm quite inexperience in this area, I can't offer any help at the moment although I'm still looking into your commit and try to get an idea from there. I'm very looking forward to any updates of yours or others on this.

Thanks again.

**Comment by LeeU1911** [comment] 2017-03-15 10:05
Hi Ben,

Recently I came across this article[https://jfconavarrete.wordpress.com/2014/09/15/make-spring-security-context-available-inside-a-hystrix-command/] which makes `Spring Security Context` available inside a hystrix command which typically runs in a separate thread from the main thread. Would this hint anything useful in our case?

Thanks.

**Comment by nebhale** [comment] 2017-03-15 13:06
While the Hystrix case itself doesn't work for us, the general idea is what we're pursuing.  Coming in a future version of Reactor (3.1?) is the3 ability to attach "context" to a flow.  That context will be transfer across thread boundaries and coordinated properly without user intervenation.  @smaldini can elaborate more/point at discussions.  I'd implement the TokenProvider by storing the `SecurityContext` In that flow context and retrieve when necessary.

**Comment by smaldini** [comment] 2017-03-15 13:10
I confirm its coming for 3.0.6/3.1.M1 and its a major story for us and a unique alternative to thread local context passing in reactive world.

**Comment by LeeU1911** [comment] 2017-03-16 06:21
Thank you both. Very helpful info. I can't wait for these to be available.

**Comment by nebhale** [comment] 2017-10-26 17:06
Dupe of #517

**Closed** 2019-03-13 19:03 UTC
Labels: client
