### ISSUE TITLE
unmap-routes will stop application

### ISSUE THREAD

**Issue by a-thaler** [cloudfoundry/cf-java-client#549] opened 2016-08-08 12:28 UTC
A call to DefaultCloudFoundryOperations.routes().unmap(...) will unmap the route but also stops the application. If you have multiple routes mapped and want to remove just one, you get into problems.

Reason seems to be in ReactorRoutes.removeApplication, here the "apps" and "routes" path is in wrong order, it should be:
builder.pathSegment("v2", "routes", request.getRouteId(), "apps", request.getApplicationId())

**Comment by twoseat** [comment] 2016-08-08 14:44
Thanks for raising this @a-thaler. I'm a little puzzled as the potential solution you provided is what we already have (and matches the api doc):

```
    @Override
    public Mono<Void> removeApplication(RemoveRouteApplicationRequest request) {
        return delete(request, Void.class, builder -> builder.pathSegment("v2", "routes", request.getRouteId(), "apps", request.getApplicationId()));
    }
```

Can you confirm the date of the cf-java-client library you're currently using?

**Comment by twoseat** [comment] 2016-08-08 15:23
@a-thaler Investigating further I've found the problem. It's possible to either remove an app from a route, or remove a route from an app. We're doing the former, but we should be doing the latter. I'll add a fix for this. So basically, you're right! Thanks!

**Comment by a-thaler** [comment] 2016-08-08 15:41
@twoseat I'm sorry, indeed I copy/pasted the existing version, not the fixed one, the fixed one should be

    return delete(request, Void.class, builder -> builder.pathSegment("v2", "apps", request.getApplicationId(), "routes", request.getRouteId()));

That path I have from the CLI tool and works fine for me.
Thanks for the investigation.

**Comment by twoseat** [comment] 2016-08-08 15:45
For your reference, note that the request is correct and won't be changed - the problem is we're using the wrong request. There's an app...route and a route...app version, both of which are valid in different circumstances. So the underlying methods are correct, we were just calling the wrong one from the next level up!

**Comment by twoseat** [comment] 2016-08-08 16:03
@a-thaler I believe this is now fixed, please let me know if you see problems once you've updated.

**Closed** 2016-08-08 16:02 UTC
Labels: in progress

**Comment by a-thaler** [comment] 2016-08-09 07:42
@twoseat works fine for me, thanks for the fix
