### ISSUE TITLE
2.8.0 client  throwing error when using with 1.8 PCF version 

### ISSUE THREAD

**Issue by mohanpindyala** [cloudfoundry/cf-java-client#734] opened 2017-04-19 05:07 UTC
I updated the client from 2.1.0 to 2.8.0  and using against 1.8 pcf version . Getting following error 

BTW client is working perfectly fine with 1.9 and 1.10 versions of pcf

```
org.cloudfoundry.client.v2.ClientV2Exception: CF-StatsUnavailable(200002): Stats unavailable: Stats server temporarily unavailable.
2017-04-18T21:59:41.14-0700 [APP/0]      OUT 	at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$0(ErrorPayloadMapper.java:47)
2017-04-18T21:59:41.14-0700 [APP/0]      OUT 	at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$10(ErrorPayloadMapper.java:108)
2017-04-18T21:59:41.14-0700 [APP/0]      OUT 	at
```

PCF elastic runtime version : v1.8.29-build-2

Client jars versions 
```
<cloudfoundry-client-reactor.version>2.8.0.RELEASE</cloudfoundry-client-reactor.version>
<cloudfoundry-operations.version>2.8.0.RELEASE</cloudfoundry-operations.version>
<reactor-core.version>3.0.6.RELEASE</reactor-core.version>
<reactor-netty.version>0.6.2.RELEASE</reactor-netty.version>
```

Also attached is the full error logs from client [cflogs.txt.zip](https://github.com/cloudfoundry/cf-java-client/files/931860/cflogs.txt.zip)

**Comment by nebhale** [comment] 2017-04-19 15:59
That error indicates that there's something wrong between the Cloud Controller and the Stats Server.  We [already handle the case](https://github.com/cloudfoundry/cf-java-client/blob/v2.8.0.RELEASE/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java#L656) where an application is not yet running and does not have stats, but this is different.  This is the Cloud Controller saying that it couldn't make contact with the stats server itself; the client isn't involved.

We're testing against 1.8.39 at the moment so I'd upgrade to the latest version of 1.8 to be sure that there are no known issues that you're walking into.  After that, I'd make contact with the CAPI team to determine if they have made some sort of change that you might be having an issue with.

**Comment by mohanpindyala** [comment] 2017-04-19 18:46
Thanks @nebhale  , let me give it a shot

**Comment by harirongali** [comment] 2017-04-19 18:48
@nebhale Do we need to upgrade opsmanager director as well or just elastic runtime?
our opsmanager director is @ 1.8.14.0 and elastic runtime @ 1.8.29-build.2

**Comment by nebhale** [comment] 2017-04-19 19:03
Should be only the Elastic Runtime; that's where the Cloud Controller lives.

**Comment by mohanpindyala** [comment] 2017-04-20 18:40
@nebhale  we still see same error , see latest logs 
[cflogs2.txt.zip](https://github.com/cloudfoundry/cf-java-client/files/945134/cflogs2.txt.zip)

**Comment by nebhale** [comment] 2017-04-20 18:57
Have you made contact with the CAPI team to enquire about what might cause their API to returned a `200002`?  We don't see the same behavior on our 1.8 test systems, even though they are testing a variety of stopped/started/partially stopped/partially started applications.

**Comment by mohanpindyala** [comment] 2017-04-20 20:15
@nebhale  whom should I contact in CAPI ? I don't know the channel or direct contact

**Comment by nebhale** [comment] 2017-04-20 21:02
The CAPI team is available at `#capi` in https://cloudfoundry.slack.com or via issues in the [Cloud Controller Repository](https://github.com/cloudfoundry/cloud_controller_ng).

**Comment by michaelxupiv** [comment] 2017-04-21 22:29
@mohanpindyala and I went through CC logs to trace down the error. Basically, their app is hitting the `/v2/apps/guid/stats` endpoint. CC fetches stats information by communicating with TPS, which then provides information about the app. One of the things TPS does is communicate with TrafficController for container metrics. 

We see that their TPS-listener makes a request to fetch container metrics. However, that request results in a `"message":"tps-listener.fetching-container-metrics-failed",data":{"error":"unknown issue when making HTTP request to Loggregator"`. We took a look at the traffic controller and doppler logs, which were surprisingly short and didn't find anything to go off of.

It is weird that an older version of your client works but the newer one doesn't, because it looks like CC and TPS are just in the business of constructing url's (these url's are the same except for guids), and it just records the response from their requests. 

A possible next step would be to contact Loggregator and see if they can debug what is happening on their end.

Tim & Mike - @tcdowney @michaelxupiv

**Comment by nebhale** [comment] 2017-04-21 22:36
@mohanpindyala @tcdowney @michaelxupiv I'm happy to make some changes if you find something conclusive, but we haven't made changes to that logic since 2.0.0.M7 (according to GitHub), so it feels environmental.

**Comment by nebhale** [comment] 2017-05-08 17:30
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by mohanpindyala** [comment] 2017-05-23 21:04
I was on paternity leave, please re-open the issue. Still not resolved

**Comment by ahevenor** [comment] 2017-05-24 21:15
The loggregator reviewed this issue and we were not able to find anything conclusive but have the following theory. The logging endpoint moved from `logging_endpoint` to `doppler_logging_endpoint`. We were not able to confirm that the timing lines up but this would likely result in the error you are seeing.

**Comment by nebhale** [comment] 2017-05-24 21:23
@ahevenor The issue is that the Cloud Controller is returning ` CF-StatsUnavailable(200002): Stats unavailable: Stats server temporarily unavailable.` for a call.  I'm not sure where the contents of `/v2/info` would come to bear on that problem.

**Comment by mohanpindyala** [comment] 2017-05-24 23:38
@nebhale @ahevenor 

ok after extensive debugging looks like I found a fix.  The scenario is I have 200 apps in my space where I am running this cf java client.
 Before my code was, see extra subscribe instead of returning.
```
  cfOperations.applications()
                        .list()
                        .flatMap(app -> {
                            try {
                                cfOperations.applications()
                                            .get(GetApplicationRequest.builder().name(app.getName())
                                                                      .build())
                                            .then(appDetail -> {
                                                return cfOperations
                                                        .applications()
                                                        .getEnvironments(GetApplicationEnvironmentsRequest.builder

                                                                ().name

                                                                (app.getName()).build())
                                                        .then(appEnvDetail -> {

                                                            buildStatusAndNotify(appDetail, appEnvDetail);
                                                            return Mono.empty();
                                                        });
                                            })
                                            .doOnError(err -> {
                                                logger.error("failed to send notifications for app {}, error {}",
                                                        app, err);
                                            **}).subscribe();**
                            } catch (Throwable ex) {
                                logger.error("Failed due to error", ex);
                            }
                            return Mono.empty();

                        }, 1)
                        .doOnError(err -> {
                            logger.error("failed to send notifications for apps {}", err);
                        })
                        .subscribe();
```

Changed the code to have single subscribe 
```
 cfOperations.applications()
                        .list()
                        .flatMap(app -> {
                            try {
                                **return cfOperations.applications()**
                                            .get(GetApplicationRequest.builder().name(app.getName())
                                                                      .build())
                                            .then(appDetail -> {
                                                return cfOperations
                                                        .applications()
                                                        .getEnvironments(GetApplicationEnvironmentsRequest.builder()
                                                                                                          .name(app.getName())
                                                                                                          .build())
                                                        .then(appEnvDetail -> {

                                                            buildStatusAndNotify(appDetail, appEnvDetail);
                                                            return Mono.empty();
                                                        });
                                            })
                                            .doOnError(err -> {
                                                logger.error("failed to send notifications for app {}, error {}",
                                                        app, err);
                                            });
                            } catch (Throwable ex) {
                                logger.error("Failed due to error", ex);
                            }
                            return Mono.empty();

                        }, 1)
                        .doOnError(err -> {
                            logger.error("failed to send notifications for apps {}", err);
                        })
                        .subscribe();

```
It started working.  Does that mean stats server was overloaded with calls before ? it can't handle the traffic of 200 calls ? Enlighten me please :) and also why it works in 1.9 , 1.10 is a puzzle still without any change to code.

**Comment by nebhale** [comment] 2017-05-24 23:50
I do not believe that it was overloaded.  You cannot introduce multiple subscribes within a flow, as there's no ordering if you do that.  What was happening was that it was off to get status before the application had even been started.  Even the `try/catch` doesn't mean anything in a reactive flow, errors are only passed to the subscriber, never raised within the closures of a flow.

**Comment by mohanpindyala** [comment] 2017-05-24 23:53
all the 200 apps are up and running, they never stopped. This code runs on a scheduler every 2 minutes and reports status of each app to our system.

**Comment by mohanpindyala** [comment] 2017-05-25 00:15
@nebhale  It is indeed overloaded, I increased flatmap concurrency to 50 and I see the same issue. Do you agree now ?

```
UT reactor.core.Exceptions$BubblingException: org.cloudfoundry.client.v2.ClientV2Exception: CF-StatsUnavailable(200002): Stats unavailable: Stats server temporarily unavailable.
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:292)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoThenMap$ThenMapMain.onError(MonoThenMap.java:164)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoThenMap$ThenMapMain$ThenMapInner.onError(MonoThenMap.java:247)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxResume$ResumeSubscriber.onError(FluxResume.java:101)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxResume$ResumeSubscriber.onError(FluxResume.java:98)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:192)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoThenMap$ThenMapMain.secondError(MonoThenMap.java:184)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoError.subscribe(MonoError.java:51)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:351)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:150)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:335)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:125)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	... 42 common frames omitted
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	reactor.core.publisher.Mono.checkpoint(Mono.java:1403)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	org.cloudfoundry.util.tuple.TupleUtils.lambda$function$7(TupleUtils.java:65)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:169)
2017-05-24T17:13:12.47-0700 [APP/0]      OUT 	reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.ja
```

**Comment by nebhale** [comment] 2017-05-25 13:09
I have no opinion on whether the stats server can be overloaded or not.  I don't have any insight into the internals of the system, so it's hard to judge whether or not being overloaded would cause that error.  Beyond that fact though, the disconnected `subscribe` in the middle of another flow is effectively unsupported with Reactor.  It leads to all sorts of unpredictable behavior.

**Comment by mohanpindyala** [comment] 2017-05-25 14:16
I actually removed that subscribe and put concurrency as 50,  still seeing the same error.

**Comment by nebhale** [comment] 2017-05-25 16:04
The the issue wouldn't seem to be with the Java Client.  I'll close this out.

**Closed by nebhale** 2017-05-25 16:04 UTC
