### ISSUE TITLE
@Profile not Autoconfiguring Doppler, Uaa, and CloudFoundryClient with the specified profile's attributes

### ISSUE THREAD

**Issue by Velosoda** [cloudfoundry/cf-java-client#1073] opened 2020-10-30 13:29 UTC
I have a small application whos purpose is to show the status of each application running in our PCF. One of the challenges I've had is trying to get the status from multiple foundries. I set up 3 configuration classes (on for each Foundry) and 3 profiles that have the login info needed to access all 3 foundries. 
```
@Configuration
@Setter
@Getter
@ConfigurationProperties(prefix = "dev.spring.cloud.cloudfoundry")
//I put 'dev' in the profile because that seemed to be the only way spring was actually reading in the values 
@RequiredArgsConstructor
public class PcfConfigurationDev {

    private final CloudFoundryClient cloudFoundryClient;
    private final UaaClient uaaClient;
    private final DopplerClient dopplerClient;
    private String username;
    private String password;
    private String url;
    private String skipSslValidation;

    @Profile("pcfDev")
    @Bean
    public DefaultCloudFoundryOperations.Builder buildDevPcfConnection() {
        System.out.println("User: " + getUsername());
        System.out.println("Password: " + getPassword());
        System.out.println("URL: " + getUrl());
        System.out.println(getSkipSslValidation());


        final DefaultCloudFoundryOperations.Builder builder = DefaultCloudFoundryOperations.builder()
                .dopplerClient(getDopplerClient())
                .uaaClient(getUaaClient())
                .cloudFoundryClient(getCloudFoundryClient());
        return builder;
    }
}
```
When I run in debug mode the Uaaclient has API Host from another profile, specifically the last profile to be active in my list of active profiles. But the password and username here contain the correct values from the specified profile. I am more than certain I'm setting this up incorrectly so if possible please let me know what is the correct way to do this. (Not sure why the mark up is weird sorry about that)

**Comment by twoseat** [comment] 2020-11-02 11:04
Does this work if you strip it down to a single available profile? I'm not seeing anything obviously wrong.

**Comment by Velosoda** [comment] 2020-11-02 14:55
Ive adjusted my code to look like this 
`
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.cloudfoundry.client.CloudFoundryClient;
import org.cloudfoundry.doppler.DopplerClient;
import org.cloudfoundry.operations.DefaultCloudFoundryOperations;
import org.cloudfoundry.uaa.UaaClient;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;


@Configuration
@Profile("pcfDev")
@Setter
@Getter
@ConfigurationProperties(prefix = "spring.cloud.cloudfoundry")
@RequiredArgsConstructor
public class PcfConfigurationDev {

    private final CloudFoundryClient cloudFoundryClient;
    private final UaaClient uaaClient;
    private final DopplerClient dopplerClient;
    private String username;
    private String password;
    private String url;
    private String skipSslValidation;

    @Bean
    public DefaultCloudFoundryOperations.Builder buildDevPcfConnection() {
        System.out.println("User: " + getUsername());
        System.out.println("Password: " + getPassword());
        System.out.println("URL: " + getUrl());
        System.out.println(getSkipSslValidation());


        final DefaultCloudFoundryOperations.Builder builder = DefaultCloudFoundryOperations.builder()
                .dopplerClient(getDopplerClient())
                .uaaClient(getUaaClient())
                .cloudFoundryClient(getCloudFoundryClient());
        return builder;
    }
}
`
Ive removed all the other profiles from being active minus this one, deleted the other configurations, and removed "dev" parent in the yaml file so now it just looks like "spring.cloud.cloudfoundry". I ran a test and can confirm it ran correctly. I then added one more configuration for my UAT Foundry (Created the class activated the profile and set up the yaml the same way as DEV) and the dev bean now has the properties of the UAT Profile

**Comment by Velosoda** [comment] 2020-11-04 16:25
I just changed the order of active profiles so that my pcfDev Profile is last and pcfUat comes before it and the pcfDev Properties are appearing. 
(In other words -Dspring.profiles.active=...,pcfUat,pcfDev)

**Comment by twoseat** [comment] 2020-11-05 15:29
Does switching the order just reverse the problem (i.e. the UAT bean has the properties of the DEV Profile)?

**Comment by Velosoda** [comment] 2020-11-05 16:13
@twoseat Yes as mentioned above. No matter what all my configuration beans contain the info from the last active profile

**Comment by dmikusa-pivotal** [comment] 2021-06-04 15:41
It's been a while, but following up on this. What you're describing sounds more like a problem with the initialization and structure of your application and not the cf-java-client. I don't think it would matter, for example, if you pulled out the cf-java-client and used placeholder classes that just stored the values. You'd have the same issue when the beans are created, they are just not getting the information in the order that you expect.

Since it's more general, if you still are having issues with this, I would suggest you post a question on [StackOverflow](https://stackoverflow.com/questions/tagged/spring-boot). 

I'm going to close this ticket as it's been for a while and I don't think it's an issue with cf-java-client. If you suspect a bug with the cf-java-client and you can provide a sample app with detailed steps to reproduce the issue, please reopen and attach that information. Thanks

**Closed by dmikusa-pivotal** 2021-06-04 15:41 UTC
Labels: question, triaged
