### ISSUE TITLE
SSLPeerUnverifiedException with trustSelfSignedCert=true

### ISSUE THREAD

**Issue by borlander** [cloudfoundry/cf-java-client#252] opened 2015-01-14 12:19 UTC
Can you please take a look at the problem described at https://devnet.jetbrains.com/message/5532547#5532547

AFAIK, the actual version of CloudFoundry integration for IDEA is based on cloudfoundry-client-lib of version 1.0.2. In the code, enabling of the 'Trust self-signed certificates' checkbox leads directly to the instantiantion of CloudFoundryClient class with the trustSelfSignedCert argument set to 'true'. 

According to available docs, this should prevent 'javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated' error, while the error still can be reproduced. Is it a known issue of the library? Are there any ways to enable additional debug output which may help to identify the problem? 

If needed I can provide any additional information, just let me know. 
Thanks in advance

**Comment by scottfrederick** [comment] 2015-01-14 18:05
There are no known issues around the `trustSelfSignedCerts` functionality in the library. 

The checks performed when `trustSelfSignedCerts` is enabled are pretty strict. See https://github.com/cloudfoundry/cf-java-client/issues/170#issuecomment-44349875 for more details on the checks that are performed. Can you verify that the self-signed certs you are using meet those requirements? 

Beyond that, we'd have to see what the IDEA plugin is doing with the library to help figure out why it isn't working for you.

**Comment by scottfrederick** [comment] 2015-04-10 17:49
@borlander I'm going to close this issue, since we don't have any information that the problem is in the client lib. We can re-open later if JetBrains can give additional info on what's causing the issue in their plugin.

**Closed by scottfrederick** 2015-04-10 17:49 UTC
Labels: blocked, client-lib
