### ISSUE TITLE
Uploading application bits > 16 kb -> PrematureCloseException

### ISSUE THREAD

**Issue by FaulhabeJ001** [cloudfoundry/cf-java-client#1072] opened 2020-10-13 11:25 UTC
I want to use the `defaultCloudFoundryOperations.applications().pushManifest(pushApplicationManifestRequest)` method to push an application to a Cloud-Foundry instance (e.g. `api.run.pivotal.io`) using the `cloudfoundry-client` library in a spring boot app.

But if the referenced zip file is > 16kb a `reactor.netty.http.client.PrematureCloseException` is thrown and the content of the zip-file isn´t uploaded. So the app could not start. If the referenced zip-file is < 16 kb the upload works properly with any app (aSpringBoot.zip, aStaticFile.zip; no matter of the structure or content).
It´s important to know that the problem occurs only calling the upload-ressource for the zip using the client-library: `PUT /v2/apps/:guid/bits`. Every other http-call works properly. In addition, there´s no problem calling the `PUT /v2/apps/:guid/bits` resource with a file > 16kb with Postman. Besides, the CLI works fine with zips > 16kb, too. 

Setting of the app using the client-library:
- `spring-boot-starter-parent: 2.3.3.RELEASE`
- `cloudfoundry-client-reactor: 4.10.0.RELEASE`
- `cloudfoundry-operations: 4.10.0.RELEASE`

files to upload:
[static_bigger.zip](https://github.com/cloudfoundry/cf-java-client/files/5371197/static_bigger.zip)
[static_small.zip](https://github.com/cloudfoundry/cf-java-client/files/5371198/static_small.zip)

DefaultCloudFoundry-Configuration:

```
package tmp.apps.CapiOperator.config;

import org.cloudfoundry.client.CloudFoundryClient;
import org.cloudfoundry.doppler.DopplerClient;
import org.cloudfoundry.operations.DefaultCloudFoundryOperations;
import org.cloudfoundry.reactor.ConnectionContext;
import org.cloudfoundry.reactor.DefaultConnectionContext;
import org.cloudfoundry.reactor.ProxyConfiguration;
import org.cloudfoundry.reactor.TokenProvider;
import org.cloudfoundry.reactor.client.ReactorCloudFoundryClient;
import org.cloudfoundry.reactor.doppler.ReactorDopplerClient;
import org.cloudfoundry.reactor.tokenprovider.PasswordGrantTokenProvider;
import org.cloudfoundry.reactor.uaa.ReactorUaaClient;
import org.cloudfoundry.uaa.UaaClient;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Lazy;

import java.util.Optional;

@Configuration
@EnableAutoConfiguration
public class CloudFoundryOperationsConfiguration {

    private DebugProperties debugProperties;

    public CloudFoundryOperationsConfiguration(DebugProperties debugProperties) {
        this.debugProperties = debugProperties;
    }

    @Bean
    ReactorCloudFoundryClient cloudFoundryClient(ConnectionContext connectionContext, TokenProvider tokenProvider) {
        return ReactorCloudFoundryClient.builder()
                .connectionContext(connectionContext)
                .tokenProvider(tokenProvider)
                .build();
    }

    @Bean
    @Lazy
    DefaultCloudFoundryOperations cloudFoundryOperations(CloudFoundryClient cloudFoundryClient,
                                                         DopplerClient dopplerClient,
                                                         UaaClient uaaClient,
                                                         @Value("${cf.organization}") String organization,
                                                         @Value("${cf.space}") String space) {
        return DefaultCloudFoundryOperations.builder()
                .cloudFoundryClient(cloudFoundryClient)
                .dopplerClient(dopplerClient)
                .uaaClient(uaaClient)
                .organization(organization)
                .space(space)
                .build();
    }

    @Bean
    DefaultConnectionContext connectionContext(@Value("${cf.apiHost}") String apiHost) {
        return DefaultConnectionContext.builder()
                .apiHost(apiHost)
                .additionalHttpClientConfiguration(httpClient -> httpClient.wiretap(debugProperties.isWiretap()))
                .proxyConfiguration(debugProperties.getProxy().isActive() ? getProxy() : Optional.empty())
                .skipSslValidation(debugProperties.isSkipssl())
                .build();
    }

    private Optional<ProxyConfiguration> getProxy() {
        return Optional.of(ProxyConfiguration.builder()
                .host(debugProperties.getProxy().getHost())
                .port(debugProperties.getProxy().getPort())
                .build());
    }

    @Bean
    ReactorDopplerClient dopplerClient(ConnectionContext connectionContext, TokenProvider tokenProvider) {
        return ReactorDopplerClient.builder()
                .connectionContext(connectionContext)
                .tokenProvider(tokenProvider)
                .build();
    }

    @Bean
    PasswordGrantTokenProvider tokenProvider(@Value("${cf.password}") String password,
                                             @Value("${cf.username}") String username) {

        return PasswordGrantTokenProvider.builder()
                .password(password)
                .username(username)
                .build();
    }

    @Bean
    ReactorUaaClient uaaClient(ConnectionContext connectionContext, TokenProvider tokenProvider) {
        return ReactorUaaClient.builder()
                .connectionContext(connectionContext)
                .tokenProvider(tokenProvider)
                .build();
    }

}
```

createApp-method:
```
    public void createApp(String appName, Application appEntity) {
        PushApplicationManifestRequest request = PushApplicationManifestRequest
                .builder()
                .manifest(buildApplicationManifest(appName, appEntity))
                .noStart(false)
                .build();

        Mono<Void> createRequest = cfOperations.applications().pushManifest(request)
                .doOnSubscribe(subscription -> System.out.println("pushing manifest for application: "))
                .doOnSuccess(aVoid -> System.out.println("pushed manifest for application: "));
        createRequest.block();
    }

```

Stacktrace if zip > 16kb

```
reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body



reactor.core.Exceptions$ReactiveException: reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body

	at reactor.core.Exceptions.propagate(Exceptions.java:393)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1680)
	at tmp.apps.CapiOperator.service.AppService.createApp(AppService.java:36)
	at tmp.apps.CapiOperator.service.AppServiceTest.createApp(AppServiceTest.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 66 more
Caused by: reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoDoFinallyFuseable] :
	reactor.core.publisher.Mono.checkpoint(Mono.java:1879)
	org.cloudfoundry.reactor.client.v2.applications.ReactorApplicationsV2.upload(ReactorApplicationsV2.java:245)
Error has been observed at the following site(s):
	|_ Mono.checkpoint ⇢ at org.cloudfoundry.reactor.client.v2.applications.ReactorApplicationsV2.upload(ReactorApplicationsV2.java:245)
	|_ Mono.checkpoint ⇢ at org.cloudfoundry.operations.applications.DefaultApplications.pushManifest(DefaultApplications.java:431)
Stack trace:



Process finished with exit code -1
```

**Comment by FaulhabeJ001** [comment] 2020-10-14 10:53
> Thanks for the report @FaulhabeJ001. I've tried reproducing this on our test system and "it works on my machine", so I don't have a simple answer for you. This sort of error can appear if the server is somehow set to close the connection, though the fact that you can complete the upload outside of the client makes that unlikely. So a few things for you to check first:
> 
> * Are your dependencies overriding our netty dependencies?

The test/bug-Project is very lean. I can´t see any overrides of the netty dependencies.

> * Can you try running outside of junit? It's an outside chance, but I know it can sometimes mess with threading.

I tried, but unfortunately the same effect.

> * Can you get a tcp dump of the connection closing.

I have to check this and will let you know and if possible upload it here.

I thought its best if you can see the exact code. So I have created the following repository for you that you can see exactly whats going on: https://github.com/FaulhabeJ001/CapiOperatorTest

**Comment by twoseat** [comment] 2020-10-15 07:42
Thanks for the excellent, clean example. That fails on my machine (in a good way!) so I have something to work with.

**Comment by twoseat** [comment] 2020-10-16 14:23
I have mixed news. The good news is that the problem goes away if you avoid using `.block`. For example, instead of:
```
createRequest.block();
```
using:
```
        CountDownLatch latch = new CountDownLatch(1);
        createRequest.subscribe(System.out::println, t -> {
            t.printStackTrace();
            latch.countDown();
        }, latch::countDown);

        latch.await();
```
allows the upload to complete. In general using `.block()` is a code smell, so it should only be used if you're sure you need it.

The bad news is that I can't (yet) explain quite why this is. In theory the `.block()` should be waiting for a signal that should only be emitted when the upload is completed (or fails). It appears that something (possibly the CFJC, possibly something in reactor more generally) is emitting a `next` that triggers the block. I'll keep digging at that, but for now hopefully this will get you going again.

**Comment by FaulhabeJ001** [comment] 2020-10-22 14:41
Thanks a lot for the answer. I tried the suggested solution but unfortunately I get the same error message/result as before (small works; big fails). I have adapted the sample projekt:

 https://github.com/FaulhabeJ001/CapiOperatorTest/commit/570f95222ab77757048b0404a5ef3470a8ea4638

Does this adjustment correspont to your proposal?

**Comment by twoseat** [comment] 2020-10-26 09:39
Well this is very interesting. If I run your sample code the smaller fails, but the bigger fails with an invalid zip error. Having confirmed that the zip is valid that makes me think there's a timing problem going on - the zip is valid, but the file that arrived at the CF instance isn't because the transfer was truncated. Weirdly I've also tried a much larger file (>100MB) and that seems to work OK. I'll keep investigating.

**Comment by FaulhabeJ001** [comment] 2020-11-06 14:20
Did you already find something? 

We also have another question. I would like to explain the background to you:

We are implementing a tool, which takes a complete declaration of a space with apps and services and creates a space in Cloud Foundry with it. In a nutshell, it translates a declarative yml to the corresponding imparative cf instructions (like a kubernetes yml, but processed outside the platform). If the yml changes, the tool adapts the cf space accordingly.

To implement this functionality, the tool uses the cf java client library (therefore the upload functionality is very important for us). Furthermore we need the functionality of a rolling update / zero-downtime concept. It seems that this is already implemented in capi v3 and cli >= v6. Additionally, I assume that the cf-java-client contains this functionality because there are some entities like "Deployment" and "DeploymentStrategy".

https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html
https://github.com/cloudfoundry/cf-java-client/tree/main/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3

Question: 
Is there already the possibility to conduct a rolling update with the operations-layer of the cf-java-client? If not, is it on your agenda?

**Comment by twoseat** [comment] 2020-11-06 14:26
Hi @FaulhabeJ001 my apologies, some internal work and getting out the next release distracted me from this, but I'll be back on it on Monday. In the meantime I can tell you that I am working on incorporating capi v3 and the corresponding cli functionality (hence the latest release!) I don't have a specific schedule for that, but we're doing new releases alongside each Spring Boot release (which tend to come out monthly), and in each release you should see new functionality.

**Comment by twoseat** [comment] 2020-12-01 12:24
Hi @FaulhabeJ001 I did some work on this and then got diverted again. Now I've come back to it I can't get your sample app to fail any more. Can you confirm it's still causing problems for you? I have no idea why it would work, as nothing has changed in my setup (except for my new, faster Mac?)

**Comment by FaulhabeJ001** [comment] 2020-12-10 15:53
Hi @twoseat . The problem is that it is not possible to upload the static_big.zip (static_small.zip) works fine. I started the tests again to verify that the problem still exists:

- AppServiceTest.createApp_Mini() -> works fine
- AppServiceTest.createApp_Bigger() -> upload fails (i can see the app in run.pivotal.io, but it is stopped, because the app is not uploaded correctly) see:
```
org.cloudfoundry.client.v2.ClientV2Exception: CF-AppBitsUploadInvalid(160001): The app upload is invalid: Invalid zip archive.
	at org.cloudfoundry.util.JobUtils.getError(JobUtils.java:103)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoIgnoreElements] :
	reactor.core.publisher.Mono.checkpoint(Mono.java:1879)
	org.cloudfoundry.operations.applications.DefaultApplications.pushManifest(DefaultApplications.java:431)
Error has been observed at the following site(s):
	|_ Mono.checkpoint ⇢ at org.cloudfoundry.operations.applications.DefaultApplications.pushManifest(DefaultApplications.java:431)
Stack trace:
		at org.cloudfoundry.util.JobUtils.getError(JobUtils.java:103)
...
...
```

I tried the tests with three different setups (my Mac, my Windows-pc, Windows in our organization). Same error on each machine. Also, I tried it with different Clound-Foundry instances (e.g. run.pivotal.io and cf from our org) :-(.

Are you sure the uploads are working on your machine?

**Comment by FaulhabeJ001** [comment] 2021-01-20 19:07
Hi, we have updated the project to the recent version of cloudfoundry client to 5.1.0.RELEASE. Unfortunately the uploading problem doesn´t disapper. In addition to the existing behaviour there are some new problems:

- the application doesn´t start anymore without the explicit dependency reactor-core (3.4.2) (see pom) ... `Caused by: java.lang.ClassNotFoundException: reactor.core.publisher.Sinks`

- with explicit dependency reactor-core the app starts but with warning:  `WARN  [reactor-http-nio-1] org.cloudfoundry.reactor.client.CloudFoundryClientCompatibilityChecker: Client supports API version 2.150.0 and is connected to server with API version 2.145.0. Things may not work as expected`. I don´t know if the version discrepancy is responsible for the lasting upload problem, but I don´t think so, because the upload errors are exactly the same as before.

- wiretap for debug logs doesn´t work anymore (see creating DefaultConnectionContext in CloudFoundryOperationsConfiguration)

 Furthermore, I have improved the tests in the project. Now a passed test is equivalent to a successful upload and vice versa :-).

**Comment by vchrisb** [comment] 2021-01-25 14:53
* Dependency management is pulling in `io.projectreactor 3.3.9-RELEASE` and fails with:
```
ERROR [reactor-http-nio-1] reactor.util.Loggers$Slf4JLogger: [id: 0xac2eb6b5, L:/10.93.25.197:63607 - R:login.run.pcfone.io/10.212.31.5:443] Error was received while reading the incoming data. The connection will be closed.
java.lang.NoClassDefFoundError: reactor.core.publisher.Sinks
	at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider$RefreshToken.<init>(AbstractUaaTokenProvider.java:274)
	
...

Caused by: java.lang.ClassNotFoundException: reactor.core.publisher.Sinks
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:768)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1067)
```

* I can reproduce the second test to fail using TAS 2.10 and OpenJDK 11.0.10 on Mac.
* TAS 2.10 is using a CF Api > 2.150.

**Comment by vchrisb** [comment] 2021-01-26 20:00
`cf-java-client` `5.1.0.RELEASE` does require `Spring Boot 2.4`. The test project is using `Spring Boot 2.3.3` though.
After updating the dependencies to `Spring Boot 2.4.2` and removing the manual `reactor.core`, I was able to run the test cases successfully. 👍 
As this issue was first reported for `cf-java-client` `4.10.0.RELEASE` and `Spring Boot 2.3.3`, I was able to reproduce the issue with these version. By updating the Spring Boot dependency to `2.3.8`, I was also able to run the test successfully with `4.10.0.RELEASE`.

**Comment by FaulhabeJ001** [comment] 2021-02-01 13:04
thx. It works, problem solved!

**Comment by dmikusa-pivotal** [comment] 2021-06-04 15:57
I'm going to close this out. In summary, it sounds like the issue has been fixed in the 4.x line if you upgrade to Spring Boot 2.3.8+ and it works in the 5.x line with Spring Boot 2.4.2+. If anyone is still seeing the problem after upgrading to those releases, please reopen this issue. Thanks.

**Closed by dmikusa-pivotal** 2021-06-04 15:57 UTC
Labels: bug, client, reactor
