### ISSUE TITLE
gradle plugin cfPush Service Unavailable error

### ISSUE THREAD

**Issue by pborbas** [cloudfoundry/cf-java-client#323] opened 2015-10-29 10:15 UTC
After changing to diego on Pivotal Web Services, the gradle plugin (1.1.2) started to fail on cfPush. The cf command line tool is working correctly. after gradle cfPush, the operation is successful on CF, but the gradle plugin's health check fails. 
I use the java buildpack with healthCheckTimeout = 180

Output:
Executing task ':frontend-web-app:cfPush' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Connecting to 'https://api.run.pivotal.io' with username '***@****'
Updating application frontend-web-app
Uploading file /***/frontend-web-app/build/libs/frontend-web-app-1.0.0-SNAPSHOT.jar
Starting frontend-web-app
GET request for "https://api.run.pivotal.io/v2/apps/****/stats" resulted in 503 (Service Unavailable); invoking error handler
:frontend-web-app:cfPush FAILED

Stacktrace:
Caused by: org.springframework.web.client.HttpServerErrorException: 503 Service Unavailable
	at org.cloudfoundry.client.lib.rest.CloudControllerResponseErrorHandler.handleError(CloudControllerResponseErrorHandler.java:26)
bash-3.2$
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:598)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:556)
	at org.cloudfoundry.client.lib.rest.LoggingRestTemplate.doExecute(LoggingRestTemplate.java:54)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:520)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:251)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getInstanceInfoForApp(CloudControllerClientImpl.java:1132)
	at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.doGetApplicationStats(CloudControllerClientImpl.java:1118)

**Comment by nebhale** [comment] 2015-10-29 13:22
This is a duplicated of #322.  The problem is actually a regression on the CF side and is to be fixed in https://www.pivotaltracker.com/story/show/106702544.

**Closed** 2015-11-03 17:42 UTC
