### ISSUE TITLE
 Encountered an error  about the application log when i stop app.

### ISSUE THREAD

**Issue by liuxg123** [cloudfoundry/cf-java-client#728] opened 2017-04-10 02:04 UTC
Here's my code,

LogsDao.java

```
package com.cloudfoundry.dao;

import java.util.Date;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

import javax.annotation.Resource;
import javax.websocket.Session;

import org.cloudfoundry.doppler.Envelope;
import org.cloudfoundry.doppler.StreamRequest;
import org.reactivestreams.Subscriber;
import org.reactivestreams.Subscription;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Repository;

import com.cloudfoundry.config.UserCloudFoundry;

import reactor.core.publisher.Flux;

@Repository("logsDao")
public class LogsDao {

	static Logger log = LoggerFactory.getLogger(LogsDao.class);
	
	@Resource
	UserCloudFoundry userCloudFoundry;
	
	//logs stream
	public void stream(String token, Session session, String applicationId) throws Throwable{
		System.out.println("sessionId = " + session.getId());
		final AtomicInteger count = new AtomicInteger();
        final CountDownLatch latch = new CountDownLatch(1);
        final AtomicReference<Throwable> error = new AtomicReference<>(null);
        Subscriber<Envelope> subscriber = new Subscriber<Envelope>(){
        	@Override
            public void onSubscribe(Subscription s) {
                s.request(Long.MAX_VALUE);
            }
            @Override
            public void onNext(Envelope envelope) {
                count.incrementAndGet();
                if(envelope.getLogMessage()!=null){
                	try{
                		synchronized(session){
                			if (session.isOpen()) {
                				String message = envelope.getLogMessage().getMessage();
                    			session.getBasicRemote().sendText("sessionId = "+session.getId()+",,,"+message);
                		    }
                		}
                	}catch(Exception e){
                		e.printStackTrace();
                	}
                }
            }
            @Override
            public void onError(Throwable t) {
                error.set(t);
                latch.countDown();
            }
            @Override
            public void onComplete() {
                latch.countDown();
            }
        };
        Flux<Envelope> publisher = userCloudFoundry.dopplerClient(token).stream(StreamRequest.builder()
            .applicationId(applicationId)
            .build());
        publisher.subscribe(subscriber);
        if (!latch.await(new Date().getTime(), TimeUnit.SECONDS)) {
            throw new IllegalStateException("Subscriber timed out");
        }else if(error.get() != null){
            throw error.get();
        }
	}
}
```

WebSocketLogs.java

```
package com.cloudfoundry.websocket;

import java.io.IOException;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import javax.websocket.OnClose;
import javax.websocket.OnError;
import javax.websocket.OnMessage;
import javax.websocket.OnOpen;
import javax.websocket.Session;
import javax.websocket.server.PathParam;
import javax.websocket.server.ServerEndpoint;

import com.cloudfoundry.dao.LogsDao;
import com.cloudfoundry.utils.SpringContextUtils;

@ServerEndpoint("/websocket/{token}/{applicationId}")
public class WebSocketLogs {

	LogsDao logsDao = (LogsDao) SpringContextUtils.getApplicationContext().getBean("logsDao");

	private Map<String, Session> sessionMap = new ConcurrentHashMap<>();
	@OnOpen
	public void onOpen(@PathParam("token") String token,@PathParam("applicationId") String applicationId,Session session) {
		sessionMap.put(token+applicationId, session);
		System.out.println("======================"+sessionMap.get(token+applicationId).getId());
		try {
			logsDao.stream(token, sessionMap.get(token+applicationId), applicationId);
		} catch (Throwable e) {
			e.printStackTrace();
		}
		System.out.println("Client connected  "+token);
	}
    @OnClose
    public void onClose(@PathParam("token") String token,@PathParam("applicationId") String applicationId,Session session)throws IOException{
    	if(sessionMap.get(token+applicationId).isOpen()){
    		sessionMap.get(token+applicationId).close();
    	}
    	sessionMap.remove(token+applicationId, session);
        System.out.println("Connection closed");
    }
	@OnMessage
	public void onMessage(@PathParam("token") String token,@PathParam("applicationId") String applicationId,String message) {
		try {
			sessionMap.get(token+applicationId).getBasicRemote().sendText(message);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	@OnError
	public void onError(Session session, Throwable error) {
		System.out.println("error");
		error.printStackTrace();
	}

}
```

Console output “The software in your host has stopped an established connection.” exception when i stop an app
Here's error code,
```
java.io.IOException: java.io.IOException: The software in your host has stopped an established connection.
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:315)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:258)
	at org.apache.tomcat.websocket.WsSession.sendCloseMessage(WsSession.java:606)
	at org.apache.tomcat.websocket.WsSession.doClose(WsSession.java:494)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:313)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:191)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
	at com.cloudfoundry.dao.LogsDao$1.onNext(LogsDao.java:51)
	at com.cloudfoundry.dao.LogsDao$1.onNext(LogsDao.java:1)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:370)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber$InnerSubscriber.onNext(MonoFlatMap.java:199)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:204)
	at reactor.ipc.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:319)
	at reactor.ipc.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:312)
	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:574)
	at reactor.ipc.netty.http.client.HttpClientWSOperations.onInboundNext(HttpClientWSOperations.java:140)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1228)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: The software in your host has stopped an established connection.
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1151)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:687)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:624)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:614)
	at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:94)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:494)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
	... 50 more
Connection closed
java.io.IOException: java.io.IOException:The software in your host has stopped an established connection.
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:315)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:191)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
	at com.cloudfoundry.dao.LogsDao$1.onNext(LogsDao.java:51)
	at com.cloudfoundry.dao.LogsDao$1.onNext(LogsDao.java:1)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:370)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.MonoFlatMap$FlattenSubscriber$InnerSubscriber.onNext(MonoFlatMap.java:199)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:204)
	at reactor.ipc.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:319)
	at reactor.ipc.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:312)
	at reactor.ipc.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:574)
	at reactor.ipc.netty.http.client.HttpClientWSOperations.onInboundNext(HttpClientWSOperations.java:140)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1228)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: The software in your host has stopped an established connection.
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1151)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:687)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:624)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:614)
	at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:94)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:494)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
	... 46 more
```

**Comment by liuxg123** [comment] 2017-04-10 02:30
Cloud Foundry and the application's websocket connection is not closed When I refresh the page.
The client and the server have two sessions,
Here's output app logs in page
`
sessionId = 4,,,Updated app with guid ac440bf4-f5f4-47b6-a2a8-c17de2dbb9d8 ({"state"=>"STOPPED"})

sessionId = 4,,,Exit status 0

sessionId = 4,,,[CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Pausing ProtocolHandler ["http-nio-8080"]

sessionId = 4,,,[CONTAINER] org.apache.catalina.core.StandardService           INFO    Stopping service Catalina

sessionId = 4,,,[CONTAINER] lina.core.ContainerBase.[Catalina].[localhost].[/] INFO    Destroying Spring FrameworkServlet 'springDispatcherServlet'

sessionId = 4,,,2017-04-10 02:22:40 [localhost-startStop-2] INFO  org.springframework.web.context.support.XmlWebApplicationContext862 - Closing WebApplicationContext for namespace 'springDispatcherServlet-servlet': startup date [Mon Apr 10 02:19:13 UTC 2017]; parent: Root WebApplicationContext

sessionId = 4,,,[CONTAINER] lina.core.ContainerBase.[Catalina].[localhost].[/] INFO    Closing Spring root WebApplicationContext

sessionId = 4,,,2017-04-10 02:22:40 [localhost-startStop-2] INFO  org.springframework.web.context.support.XmlWebApplicationContext862 - Closing Root WebApplicationContext: startup date [Mon Apr 10 02:19:03 UTC 2017]; root of context hierarchy

sessionId = 4,,,2017-04-10 02:22:40 [localhost-startStop-2] INFO  org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean441 - Closing JPA EntityManagerFactory for persistence unit 'default'

sessionId = 4,,,[CONTAINER] org.apache.catalina.loader.WebappClassLoaderBase   WARNING The web application [ROOT] registered the JDBC driver [com.mysql.fabric.jdbc.FabricMySQLDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.

sessionId = 4,,,[CONTAINER] org.apache.catalina.loader.WebappClassLoaderBase   WARNING The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.

sessionId = 4,,,[CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Stopping ProtocolHandler ["http-nio-8080"]

sessionId = 5,,,Updated app with guid ac440bf4-f5f4-47b6-a2a8-c17de2dbb9d8 ({"state"=>"STOPPED"})

sessionId = 5,,,Exit status 0

sessionId = 5,,,[CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Pausing ProtocolHandler ["http-nio-8080"]

sessionId = 5,,,[CONTAINER] org.apache.catalina.core.StandardService           INFO    Stopping service Catalina

sessionId = 5,,,[CONTAINER] lina.core.ContainerBase.[Catalina].[localhost].[/] INFO    Destroying Spring FrameworkServlet 'springDispatcherServlet'

sessionId = 5,,,2017-04-10 02:22:40 [localhost-startStop-2] INFO  org.springframework.web.context.support.XmlWebApplicationContext862 - Closing WebApplicationContext for namespace 'springDispatcherServlet-servlet': startup date [Mon Apr 10 02:19:13 UTC 2017]; parent: Root WebApplicationContext

sessionId = 5,,,[CONTAINER] lina.core.ContainerBase.[Catalina].[localhost].[/] INFO    Closing Spring root WebApplicationContext

sessionId = 5,,,2017-04-10 02:22:40 [localhost-startStop-2] INFO  org.springframework.web.context.support.XmlWebApplicationContext862 - Closing Root WebApplicationContext: startup date [Mon Apr 10 02:19:03 UTC 2017]; root of context hierarchy

sessionId = 5,,,2017-04-10 02:22:40 [localhost-startStop-2] INFO  org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean441 - Closing JPA EntityManagerFactory for persistence unit 'default'

sessionId = 5,,,[CONTAINER] org.apache.catalina.loader.WebappClassLoaderBase   WARNING The web application [ROOT] registered the JDBC driver [com.mysql.fabric.jdbc.FabricMySQLDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.

sessionId = 5,,,[CONTAINER] org.apache.catalina.loader.WebappClassLoaderBase   WARNING The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.

sessionId = 5,,,[CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Stopping ProtocolHandler ["http-nio-8080"]

sessionId = 5,,,[CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Destroying ProtocolHandler ["http-nio-8080"]

sessionId = 4,,,[CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Destroying ProtocolHandler ["http-nio-8080"]

sessionId = 4,,,Exit status 143

sessionId = 5,,,Exit status 143
`

**Comment by nebhale** [comment] 2017-04-10 13:37
Nothing about this seems abnormal to me.  Your server is shutting down, breaking the connection to the client.  That's what both the client and server logs say and appears to be accurate.  You may not be closing it down correctly, but I'm not a WebSocket protocol expert so I can't say.  Either way, the stack traces indicate that the problem is not in the client.

**Comment by liuxg123** [comment] 2017-04-11 03:24
I hava a question
How can i take the initiative to close the websocket connection that between my server and cloud foundry when i call stream method.
`public void stream(String token, Session session, String applicationId) throws Throwable{
	System.out.println("sessionId = " + session.getId());
	final AtomicInteger count = new AtomicInteger();
        final CountDownLatch latch = new CountDownLatch(1);
        final AtomicReference<Throwable> error = new AtomicReference<>(null);
      
        Flux<Envelope> publisher = userCloudFoundry.dopplerClient(token).stream(StreamRequest.builder()
            .applicationId(applicationId)
            .build());
        publisher.subscribe(new Subscriber<Envelope>() {

			@Override
			public void onSubscribe(Subscription s) {
				s.request(Long.MAX_VALUE);
			}

			@Override
			public void onNext(Envelope t) {
				count.incrementAndGet();
				if(t.getLogMessage()!=null){
					if(session.isOpen()){
						synchronized(session){ 
							try{
								if(t.getLogMessage().getApplicationId().equals(applicationId)){
									session.getBasicRemote().sendText(t.getLogMessage().getMessage());
								}
							}catch(Exception e){
								e.printStackTrace();
							}
						}
					}
				}
			}

			@Override
			public void onError(Throwable t) {
				System.out.println("stream method is error");
				latch.countDown();
			}

			@Override
			public void onComplete() {
				System.out.println("stream method is complete");
				latch.countDown();
			}
        	
		});
        if (!latch.await(new Date().getTime(), TimeUnit.MINUTES)) {
            throw new IllegalStateException("Subscriber timed out");
        }else if(error.get() != null){
            throw error.get();
        }
	}`
`Flux<Envelope> publisher = userCloudFoundry.dopplerClient(token).stream(StreamRequest.builder()
            .applicationId(applicationId)
            .build());
`
How can i get log from publisher?And this connect between server and clound foundry will be create,how can i close it by myself?

**Comment by nebhale** [comment] 2017-04-11 13:14
I'm not an expert in the WebSocket API, so I do not know what methods you should be calling on its API.  On the reactor side the `onXXX` methods are used to trigger side-effects (like closing a WebSocket) and I encourage you to read the [documentation on them](http://projectreactor.io/docs/core/release/reference/docs/index.html).

**Comment by liuxg123** [comment] 2017-04-14 01:30
ok,thanks a lot

**Closed** 2017-04-17 13:45 UTC
