### ISSUE TITLE
uploadApplication() on Windows

### ISSUE THREAD

**Issue by agarella** [cloudfoundry/cf-java-client#307] opened 2015-08-31 13:09 UTC
Hi,

When uploading an application to Pivotal using the cf-java-client on Windows something goes wrong. We do not run into the same issues when running the identical code on Linux or Mac OS X.

When adding an UploadStatusCallBack to get some more insight, we see that the resource size and file names are matched correctly. When checking the progress however, we see that the status changes from running to failed after only a few seconds. Also almost no bandwidth is used during the whole process, which leads us to suspect that nothing is being uploaded at all.

We have experienced the same behavior on multiple Windows 7 & Windows 8 machines.

**Comment by nebhale** [comment] 2015-10-20 23:09
Duplicate of #290

**Closed by nebhale** 2015-10-20 23:09 UTC
Labels: client-lib
