### ISSUE TITLE
Pushing manifest with changed memory settings changes size but not unit

### ISSUE THREAD

**Issue by sslavic** [cloudfoundry/cf-java-client#270] opened 2015-03-23 10:26 UTC
I'm pushing an app to CF with Bamboo CF plugin, which is using cf-java-client.
App was previously successfully pushed and started with 512M memory limit.
After modifying changed push limit from 512M to 1G, push fails, and 1M is mentioned in logs.
Changing manifest memory limit to 1024M, and pushing again is successful.

It seems that the update of app memory limit updates size but not unit of memory capacity. I'm not sure where, in Bamboo CF plugin or cf-java-client is the bug.

**Comment by davidehringer** [comment] 2015-03-23 11:25
@sslavic , I suspect that the issue is in the Bamboo plugin as all the manifest parsing logic is in it.  Can you submit at ticket in the [Bamboo plugin issue tracker](https://gaptap.atlassian.net/projects/CFBAMBOO) and include manifest examples showing the problem?

**Comment by sslavic** [comment] 2015-03-23 13:48
@davidehringer Thanks for quick reply! I've just created ticket https://gaptap.atlassian.net/browse/CFBAMBOO-127

**Comment by scottfrederick** [comment] 2015-03-23 15:17
cf-java-client just takes an [integer value for memory](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/domain/CloudApplication.java#L55-L65), no "M" or "G" suffixes in Strings, so the Bamboo plugin definitely seems like the place for this issue. Closing this one.

**Closed by scottfrederick** 2015-03-23 15:17 UTC
