### ISSUE TITLE
getApplications().getSpace() yields null organization

### ISSUE THREAD

**Issue by gregturn** [cloudfoundry/cf-java-client#312] opened 2015-09-10 05:13 UTC
Tracing through a debugger, I uncovered this structure when fetching the organization for a CF application:
```
key = {java.lang.String@11249} "entity"
value = {java.util.LinkedHashMap@11468}  size = 15
 0 = {java.util.LinkedHashMap$Entry@11471} "name" -> "production"
 1 = {java.util.LinkedHashMap$Entry@11472} "organization_guid" -> "ca7b72bd-28fe-41b2-b453-3f9024bfa786"
 2 = {java.util.LinkedHashMap$Entry@11473} "space_quota_definition_guid" -> "null"
 3 = {java.util.LinkedHashMap$Entry@11474} "allow_ssh" -> "true"
 4 = {java.util.LinkedHashMap$Entry@11475} "organization_url" -> "/v2/organizations/ca7b72bd-28fe-41b2-b453-3f9024bfa786"
 5 = {java.util.LinkedHashMap$Entry@11476} "developers_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/developers"
 6 = {java.util.LinkedHashMap$Entry@11477} "managers_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/managers"
 7 = {java.util.LinkedHashMap$Entry@11478} "auditors_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/auditors"
 8 = {java.util.LinkedHashMap$Entry@11479} "apps_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/apps"
 9 = {java.util.LinkedHashMap$Entry@11480} "routes_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/routes"
 10 = {java.util.LinkedHashMap$Entry@11481} "domains_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/domains"
 11 = {java.util.LinkedHashMap$Entry@11482} "service_instances_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/service_instances"
 12 = {java.util.LinkedHashMap$Entry@11483} "app_events_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/app_events"
 13 = {java.util.LinkedHashMap$Entry@11484} "events_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/events"
 14 = {java.util.LinkedHashMap$Entry@11485} "security_groups_url" -> "/v2/spaces/47016500-ed8c-4216-b7b3-22ad86f764cd/security_groups"
```

The code at https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/util/CloudEntityResourceMapper.java#L126-L133 is aimed at looking up **organization**, a field that doesn't appear here. It should be updated to use either **organization_guid** or **organization_url**, whichever is appropriate to retrieve the details.

**Comment by scottfrederick** [comment] 2015-09-22 20:00
Duplicate of #269

**Comment by gregturn** [comment] 2015-09-23 01:45
@scottfrederick could we add a javadoc note to explain the cost and perhaps how to handle it? That way, you could avoid future duplicate issues.

**Comment by nebhale** [comment] 2015-10-20 23:18
@gregturn This will be taken care of as part of the V2 effort.

**Closed by nebhale** 2015-10-20 23:18 UTC
Labels: client-lib
