### ISSUE TITLE
cf maven plugin doesn't recognize an env key once it is set to null value and then updated to a non null value

### ISSUE THREAD

**Issue by nagarakesh4** [cloudfoundry/cf-java-client#287] opened 2015-06-09 22:59 UTC
If an environment variable is unset and a cf maven build is performed then in all of the consecutive builds after the variable is set to a non-null value, this update will be disregarded and a null pointer exception is thrown as below

Failed to execute goal org.cloudfoundry:cf-maven-plugin:1.1.1:push-only (default-cli): An exception was caught while executing Mojo. NullPointerException

possible reason could be at https://github.com/cloudfoundry/cf-java-client/blob/ce7fd7c2f815dc5fa0aed6001fb537f713e068bf/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/domain/CloudApplication.java#L227

this code performs a toString conversion on the env key and value without any null check (a null check is done after this line of code!) thus causing a null pointer exception.

**Comment by scottfrederick** [comment] 2015-06-26 21:27
This is a duplicate of #273.

**Closed by scottfrederick** 2015-06-26 21:27 UTC
Labels: maven-plugin
